sudo: required
services: 
  - docker

before_install:
  - docker build -t hnalamwar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hnalamwar/docker-react npm run test
  # - docker run hnalamwar/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"